openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/autoservice/company/:
    get:
      operationId: listCompanys
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u0447\
        \u0442\u0435\u043D\u0438\u044F \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\
        \u0438\u0438 \u043E \u043A\u043E\u043C\u043F\u0430\u043D\u0438\u044F\u0445\
        \ \u043F\u043E \u0440\u0435\u043C\u043E\u043D\u0442\u0443 \u0430\u0432\u0442\
        \u043E."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
          description: ''
      tags:
      - api
  /api/v1/autoservice/company/{id}/:
    get:
      operationId: retrieveCompany
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u0447\
        \u0442\u0435\u043D\u0438\u044F \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\
        \u0438\u0438 \u043E \u043A\u043E\u043C\u043F\u0430\u043D\u0438\u044F\u0445\
        \ \u043F\u043E \u0440\u0435\u043C\u043E\u043D\u0442\u0443 \u0430\u0432\u0442\
        \u043E."
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041A\u043E\u043C\u043F\
          \u0430\u043D\u0438\u044F \u043F\u043E \u0440\u0435\u043C\u043E\u043D\u0442\
          \u0443 \u0430\u0432\u0442\u043E."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
          description: ''
      tags:
      - api
  /api/v1/autoservice/service/:
    get:
      operationId: listAutoServiceFromGeoIPApis
      description: "ApiView \u0434\u043B\u044F \u043F\u043E\u043B\u0443\u0447\u0435\
        \u043D\u0438\u044F \u0430\u0432\u0442\u043E\u0441\u0435\u0440\u0432\u0438\u0441\
        \u043E\u0432.\n\u0410\u0432\u0442\u043E\u0441\u0435\u0440\u0432\u0438\u0441\
        \u044B \u043E\u0442\u0441\u043E\u0440\u0442\u0438\u0440\u043E\u0432\u0430\u043D\
        \u044B \u043F\u043E \u0440\u0430\u0441\u0441\u0442\u043E\u044F\u043D\u0438\
        \u044E \u0434\u043E \u043A\u043B\u0438\u0435\u043D\u0442\u0430."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/autoservice/service/{id}/:
    get:
      operationId: retrieveRetriveAutoServiceApi
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/core/geoip/my/:
    get:
      operationId: listMyGeoIPApis
      description: "ApiView \u0434\u043B\u044F \u043F\u043E\u043B\u0443\u0447\u0435\
        \u043D\u0438\u044F \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u0433\u0435\
        \u043E\u043B\u043E\u043A\u0430\u0446\u0438\u0438 \u043A\u043B\u0438\u0435\u043D\
        \u0442\u0430.\n\u0413\u0435\u043E\u043B\u043E\u043A\u0430\u0446\u0438\u044F\
        \ \u0431\u0435\u0440\u0435\u0442\u0441\u044F \u043F\u043E IP \u0438\u0437\
        \ request."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/v1/car_models/:
    get:
      operationId: listTransports
      description: ''
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - name: brand
        required: false
        in: query
        description: brand
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transports'
          description: ''
      tags:
      - api
  /api/v1/car_models/{id}/:
    get:
      operationId: retrieveTransport
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0411\u0440\u0435\u043D\
          \u0434."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transports'
          description: ''
      tags:
      - api
  /api/v1/jobs/:
    get:
      operationId: listJobs
      description: ''
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      - name: name
        required: false
        in: query
        description: name
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Jobs'
          description: ''
      tags:
      - api
  /api/v1/jobs/{id}/:
    get:
      operationId: retrieveJob
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0420\u0430\u0431\u043E\
          \u0442\u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
          description: ''
      tags:
      - api
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          description: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u043D\u0430\u0437\
            \u0432\u0430\u043D\u0438\u0435 \u043A\u043E\u043C\u043F\u0430\u043D\u0438\
            \u0438"
          maxLength: 250
        description:
          type: string
          nullable: true
        logo:
          type: string
          format: binary
          nullable: true
        legal_address:
          type: string
          nullable: true
          maxLength: 250
      required:
      - title
    Transports:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        brand:
          type: string
          maxLength: 150
        slug:
          type: string
          maxLength: 150
      required:
      - brand
      - slug
    Jobs:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
          nullable: true
          maxLength: 150
      required:
      - title
